### ISSUE TITLE
Please to do if can by Monday if possible :)))))))

### ISSUE THREAD

**Issue by thayea2** [LightingResearchCenter/HealthyLiving#327]
- [ ] *Update 'Our role' like we talked about

- [ ] *Add CS charts/graphs (the ones Allison is able to do)

- [ ] *Add charts:

    - [ ]  Ev

    - [ ]  LPD

    - [ ]  Energy

    - [ ]  Ev:Eh ratio

  - [ ]  Lumen/Wattage-- Does this go in fixture section??

- [ ] *Update rest of background text _without_ references though! (for now)

     - [ ] *Update accordion to reflect added/deleted sections in text

- [ ] Re-add downloads :| Because I've been working on them. Please re-add to 'additional information' and include downloads in summaries of corresponding sections <3 

I'm not purposely trying to demand a lot out of you because I realize it's a super short turn around but if you can magically get a few things done without being stressed that would be so super

**Comment by MichaelvMorrison** [comment]
get this out of my face
