### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by thayea2** [LightingResearchCenter/HealthyLiving#336]
-Add all text to background (Michael)
-Add all references to background (Michael)
-Add titles for the next sections. e.g. after a summary, add the title 'Healthcare' so you see you're going into the next section. This title doesn't have to stick, but if you click on 'healthcare' on accordion it will bring you down to the title (Michael & Allison)

-Add glossary pop-ups in text- Hand select (Michael & Allison)
-Links in glossary don't open in new tab (Michael)
-Link links in text to other sections of the website-- see prompts in text (Michael)
-Downloadable PDFs- Add to 'Additional information' as well as summaries at end of each section-- Updated PDFs in repo, match to respective summary sections (Michael)
-Can/should 'Adapted from' only be visible when hovering over the image? Should all images have captions instead? What is Michael's opinion? We will change if you think it's a good tactic (Michael & Allison)

-Acknowledgements: (Michael)
Allison Thayer, M.S., B.A., is a senior research specialist at the LRC. She holds a bachelor's in architecture, and a master's of science with a concentration in lighting from Rensselaer. Allison has played a main role in the development of the structure and content of the new Healthy Living website.

Michael Morrison is a fourth year student at Rensselaer studying Information Tech and Web Sciences. Michael has played a main role in developing the code for the new Healthy Living website. 

Special thanks to:
Mariana Figueiro, Director of the LRC
David Pedler
Jean Paul Freyssinier
Charlie Jarboe
Kassandra Gonzales

**Comment by MichaelvMorrison** [comment]
replaced by #361
