### ISSUE TITLE
Missing ratio chart in single w kitchen & single

### ISSUE THREAD

**Issue by thayea2** [LightingResearchCenter/HealthyLiving#342]
![missing image](https://user-images.githubusercontent.com/50876404/77661650-4e9a7180-6f51-11ea-9ef6-883ff332fb80.JPG)

I can't seem to figure why the ratio chart won't show up in the single w kitchen or single. I named the image like it's reference is in the code, and the common area ratio chart works. I thought maybe the code was missing "d-none" but common area doesn't have it there either. Is this a coding problem or an allison problem? 
SOS (Save Our Site)

**Comment by MichaelvMorrison** [comment]
what branch are you on?
