### ISSUE TITLE
SPD ?Modal?

### ISSUE THREAD

**Issue by thayea2** [LightingResearchCenter/HealthyLiving#354]
- [ ] SPD modal: Allison has master excel sheet with information about all CCTs. Information includes graphed SPDs, EV to hit CS targets, and chart 

- Allison has modal demo. Go to folder: \\lrcroot.win.rpi.edu\public\thayea2\Website\Week of March 30 2020\SPD (MM)

- Modal will be accessed through 'resources' at top drop down and referenced when SPD is talked       about in background text. 

- [x] SPD graphs could be added as section in right panel (MM)

- [x] I loveeee the SPDs in the modal, thanks! When looking at SPD chart then changing CCT, the right panel jumps back to LPD tab. (MM)

**Comment by MichaelvMorrison** [comment]
replaced by #367
