### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by MichaelvMorrison** [LightingResearchCenter/HealthyLiving#366]
Mariana links to articles in the text, and we could have a 'Resources' tab in the 'Additional information' that gives access to all these links in one spot. 

- [x] Lighting Research Center's CS Calculator
https://www.lrc.rpi.edu/cscalculator/

- [x] UL Design Guideline: Design Guideline for Promoting Circadian Entrainment with Light for Day-Active People 
https://www.shopulstandards.com/ProductDetail.aspx?UniqueKey=36592

- [x] Guidance Document: Lighting For Health And Energy Savings
https://www.lrc.rpi.edu/programs/energy/pdf/LightingForHealthAndEnergyGuidance.pdf

- [x] Lighting Research & Technology (LR&T): The effectiveness of light-emitting diode lighting for providing circadian stimulus in office spaces while minimizing energy use
https://journals.sagepub.com/doi/full/10.1177/1477153519834604

- [x] Lighting Design and Application (LD+A): Designing with Circadian Stimulus
https://www.lrc.rpi.edu/resources/newsroom/LDA_CircadianStimulus_Oct2016.pdf

- [x] Architectural Lighting (AL): Quantifying Circadian Light and Its Impact
https://www.archlighting.com/technology/quantifying-circadian-light-and-its-impact_o

- [x] TEDMED: Why an enlightened design integrates illuminaiton
https://www.tedmed.com/talks/show?id=293012

- [x] National Institute of Health (NIH): Device To Control Circadian-Effective Light In Alzheimer's Disease Environments 
https://projectreporter.nih.gov/project_info_description.cfm?aid=9907480&icde=49456756&ddparam=&ddvalue=&ddsub=&cr=1&csb=default&cs=ASC&pball=

Do we need/want the drop-down 'resources' in that top nav bar? I think CS calculator is necessary but is there anything else? Is it worth?

**Comment by MichaelvMorrison** [comment]
Remove Resources dropdown in navbar?

**Comment by thayea2** [comment]
CS calculator, SPD modal, and CS rating would be useful to have as easy access in Resource nav bar section. For now, keep Resource drop down and put in CS calculator link and SPD modal if we get to it

**Comment by MichaelvMorrison** [comment]
> 
> 
> CS calculator, SPD modal, and CS rating would be useful to have as easy access in Resource nav bar section. For now, keep Resource drop down and put in CS calculator link and SPD modal if we get to it

Lets keep 'resources' in the navbar be other LRC links. and (needs to have a different name than resources) 'additional links' or 'helpful links' on the background page be that entire list of links
