### ISSUE TITLE
Individuals > Learn More

### ISSUE THREAD

**Issue by thayea2** [LightingResearchCenter/HealthyLiving#395]
There's just one section I see that the text wasn't updated. It's hopefully as simple as copy/pasting from 'M/D' section to 'Individual' section:

- [x] Individuals > Learn more > Horizontal and vertical illuminance
Make the same as: M/D > Information about room > Horizontal and vertical illuminance section
Also p. 17 in text document

- [x] Individuals > Learn more CS metric
Make the same as: M/D > Circadian lighting solutions > Lighting sytems
Please rename this section to "Lighitng Systems" as well
p. 18 in text document

- [x] Individuals > Learn more > CCT and Desired CCT sections
Make the same as: M/D > circadian lighting solutions > CCT systems "static vs color-tunable lighting systems" and Desired CCT
p. 19-20 in text document

- [ ] Individuals > Learn more > CS calculator:

The LRC’s web-based CS calculator has robust and flexible functionality to help lighting professionals select light sources and light levels that will increase the potential for circadian-effective light exposure in architectural spaces.

**Comment by MichaelvMorrison** [comment]
For the first bullet point here, the section you mentioned doesn't exist. Do you mean the Ev/Eh ratio section? or both the Horizontal Illuminance and the Vertical Illuminance sections?

**Comment by MichaelvMorrison** [comment]
For the third bullet point, desired CCT is not mentioned in the word doc under Individuals > Learn more, where are you getting this?

**Comment by MichaelvMorrison** [comment]
What about SPD and CS Calculator subsections?

**Comment by thayea2** [comment]
_Desired CCT_ goes with CCT static vs tunable, so it's fitting to put in this section, david just didnt know it. 

_SPD_ is talked about in the Static vs tunable CCT section so that's good, and you're right, use the following for _CS calculator_:

The LRC’s web-based CS calculator has robust and flexible functionality to help lighting professionals select light sources and light levels that will increase the potential for circadian-effective light exposure in architectural spaces.
